name: gomponents-lucide

services:
  app:
    container_name: glu_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - glu_vol_app_ssh:/root/.ssh
      - glu_vol_app_gh:/root/.config/gh
      - glu_vol_app_go_mod_cache:/root/go/pkg/mod
    stdin_open: true # docker run -i
    tty: true # docker run -t

volumes:
  glu_vol_app_ssh:
  glu_vol_app_gh:
  glu_vol_app_go_mod_cache:
