# Please always use the same golang version that
# gomponents uses to maximize compatibility
FROM golang:1.18 AS golang

# This is the actual image we will use
FROM ubuntu:24.04

# Go to a temporary directory until we install all the dependencies
RUN mkdir -p /app/temp
WORKDIR /app/temp

# Install system dependencies
RUN apt-get update && \
    apt-get install -y wget git && \
    rm -rf /var/lib/apt/lists/*

# Copy the golang binaries from the golang image
COPY --from=golang /usr/local/go /usr/local/go
ENV PATH "$PATH:/usr/local/go/bin"

# Install GitHub CLI
RUN wget https://github.com/cli/cli/releases/download/v2.46.0/gh_2.46.0_linux_amd64.tar.gz && \
    tar -xzf gh_2.46.0_linux_amd64.tar.gz && \
    mv gh_2.46.0_linux_amd64/bin/gh /usr/local/bin/gh && \
    chmod 777 /usr/local/bin/gh

# Install task
RUN wget https://github.com/go-task/task/releases/download/v3.34.1/task_linux_amd64.tar.gz && \
    tar -xzf task_linux_amd64.tar.gz && \
    mv ./task /usr/local/bin/task && \
    chmod 777 /usr/local/bin/task

# Delete the temporary directory and go to the app directory
RUN rm -rf /app/temp
WORKDIR /app

# Add the startup script on every bash session
COPY scripts/startup.sh /usr/local/bin/startup.sh
RUN echo "\n\n" >> /root/.bashrc && \
    cat /usr/local/bin/startup.sh >> /root/.bashrc

# Command just to keep the container running
CMD ["tail", "-f", "/dev/null"]