version: "3"

tasks:
  build: # Runs the build cmd to generate the lucide package
    cmds:
      - go run ./cmd/build/.
      - task fmt

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  test:
    cmds:
      - task fmt
      - go test ./...
