version: "3"

tasks:
  build: # Runs the build cmd to generate the lucide package
    cmd: go run ./cmd/build/.

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  lint:
    cmd: golangci-lint run ./...

  test:
    cmds:
      - task fmt
      - task lint
      - go test ./...
