version: "3"

tasks:
  on: # Starts the development environment and enters into the container
    cmds:
      - docker compose up -d --build
      - docker compose exec app /bin/bash

  off: # Stops the development environment
    cmd: docker compose down

  build: # Runs the build cmd to generate the lucide package
    cmds:
      - go run ./cmd/build/.
      - task fmt

  tidy:
    cmd: go mod tidy

  fmt:
    cmd: go fmt ./...

  test:
    cmds:
      - task fmt
      - go test ./...

  fixperms: # Fixes the permissions of the files in the project
    cmd: ./scripts/fixperms.sh
